const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {VaultStore}=require('../src/store.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vault-analysis-'));let store=new VaultStore(path.join(dir,'index.sqlite'));t.after(()=>{store.close();assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'vault-analysis-'));fs.rmSync(dir,{recursive:true,force:true});});const write=(name,id,project,records,extra={})=>{const file=path.join(dir,name+'.jsonl');fs.writeFileSync(file,[{type:'session_meta',payload:{id,cwd:project,thread_source:'user',...extra}},...records].map(JSON.stringify).join('\n'));return file;};return {dir,store,write};}
const msg=(text,date='2026-09-01',role='user')=>({timestamp:date+'T12:00:00Z',type:'response_item',payload:{type:'message',role,content:[{type:'text',text}]}});
test('project analysis includes multiple sessions, dated assistant events, files and candidate provenance',async t=>{const {store,dir,write}=setup(t);write('a','a','P',[msg('We decided to use SQLite. src/store.cjs'),msg('Completed release v1.0','2026-09-02','assistant')]);write('b','b','P',[msg('Need to add regression tests for src/store.cjs','2026-09-03')]);write('c','c','Other',[msg('Unrelated')]);await store.scan([dir]);const a=store.analyze({project:'P'});assert.equal(a.sessions.length,2);assert.equal(a.total,3);assert.equal(a.days.length,3);assert.equal(a.types.decision,1);assert.equal(a.types.task,1);assert.equal(a.files[0].count,2);assert.ok(a.events.every(e=>e.line>0&&e.session));assert.equal(a.events[0].basis,'inferred');assert.equal(store.analyze({project:'P',from:'2026-09-02',to:'2026-09-02'}).total,1);assert.throws(()=>store.analyze({from:'2026-10-01',to:'2026-09-01'}));});
test('recorded fork and subagent relations stay distinct and missing parents remain explicit',async t=>{const {store,dir,write}=setup(t);write('a','a','P',[msg('Root')]);write('b','b','P',[msg('Fork')],{forked_from_id:'a',git:{branch:'feature',commit_hash:'abc'}});write('c','c','P',[msg('Agent')],{source:{subagent:{thread_spawn:{parent_thread_id:'a'}}},thread_source:'subagent'});write('d','d','P',[msg('Missing parent')],{parent_thread_id:'unknown'});await store.scan([dir]);const a=store.analyze({project:'P',includeService:true});assert.equal(a.relations.find(r=>r.type==='fork').missing,false);assert.equal(a.relations.find(r=>r.type==='subagent').missing,false);assert.equal(a.relations.find(r=>r.type==='parent').missing,true);assert.equal(a.sessions.find(s=>s.sessionId==='b').git.branch,'feature');assert.ok(a.graph.edges.every(e=>['contains','mentions','mentions keyword','fork','parent','subagent'].includes(e.type)));});
test('manual annotations survive index refresh and reset, but do not silently attach to changed text',async t=>{const {store,dir,write}=setup(t);const f=write('a','a','P',[msg('Need to investigate')]);await store.scan([f]);const e=store.analyze({}).events[0];store.annotate({session:e.session,line:e.line,type:'decision',note:'Reviewed',signature:e.signature});await store.scan([f],()=>{},true);assert.equal(store.analyze({}).events[0].basis,'manual');store.annotate({session:e.session,line:e.line,type:'',signature:e.signature});assert.equal(store.analyze({}).events[0].basis,'inferred');store.annotate({session:e.session,line:e.line,type:'milestone',signature:e.signature});write('a','a','P',[msg('A different record')]);await store.scan([f],()=>{},true);assert.equal(store.analyze({}).events[0].basis,'record');assert.throws(()=>store.annotate({session:e.session,line:e.line,type:'bug',signature:e.signature}));});
test('pin and archive flags are app-owned; linked tool output remains accessible',async t=>{const {store,dir,write}=setup(t);const f=write('a','a','P',[{timestamp:'2026-09-01T12:00:00Z',type:'response_item',payload:{type:'function_call',name:'exec',call_id:'c1',arguments:'echo hi'}},{timestamp:'2026-09-01T12:00:01Z',type:'response_item',payload:{type:'function_call_output',call_id:'c1',output:'hi'}}]);const before=fs.readFileSync(f);await store.scan([f]);const id=store.list()[0].id;store.sessionFlag({session:id,pinned:true,archived:true});assert.equal(store.flags()[0].pinned,1);assert.equal(store.recordDetail({session:id,line:2}).related.length,2);assert.deepEqual(fs.readFileSync(f),before);});

test('annotation identity covers text beyond the analysis preview',async t=>{const {store,write}=setup(t);const prefix='Text '.repeat(1100);const f=write('long','long','P',[msg(prefix+'original')]);await store.scan([f]);const e=store.analyze({}).events[0];store.annotate({session:e.session,line:e.line,type:'decision',signature:e.signature});write('long','long','P',[msg(prefix+'changed')]);await store.scan([f],()=>{},true);assert.equal(store.analyze({}).events[0].basis,'record');assert.throws(()=>store.annotate({session:e.session,line:e.line,type:'task',signature:e.signature}));});
