const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {parseSession}=require('../src/parser.cjs'),{VaultStore}=require('../src/store.cjs'),{checkDestination}=require('../src/export.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vault-release-')),file=path.join(dir,'session.jsonl');let store; t.after(()=>{store?.close();const resolved=path.resolve(dir);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep+'vault-release-'));fs.rmSync(resolved,{recursive:true,force:true});});return {dir,file,db:()=>store=new VaultStore(':memory:')};}
const message=text=>({type:'response_item',payload:{type:'message',role:'user',content:[{type:'text',text}]}});
test('unexpected valid JSON and oversized raw lines do not destroy good records',async t=>{const {file}=fixture(t);fs.writeFileSync(file,[null,42,[],{payload:'bad'},message('before')].map(JSON.stringify).join('\r\n')+'\r\n'+JSON.stringify(message('x'.repeat(9*1024*1024)))+'\n'+JSON.stringify(message('after')));const r=await parseSession(file);assert.equal(r.meta.warnings,4);assert.equal(r.meta.oversized,1);assert.equal(r.meta.messages,2);assert.equal(r.records[1].line,7);});
test('legacy cumulative usage advances and mixed turns keep repeated user messages',async t=>{const {file}=fixture(t);fs.writeFileSync(file,[{type:'turn_context',payload:{turn_id:'first'}},message('Continue'),{type:'turn_context',payload:{turn_id:'second'}},{type:'event_msg',payload:{type:'item_completed',item:{type:'UserMessage',id:'u2',content:[{text:'Continue'}]}}},...[10,80].map(n=>({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{total_tokens:n}}}}))].map(JSON.stringify).join('\n'));const r=await parseSession(file);assert.equal(r.meta.messages,2);assert.equal(r.meta.tokens.total_tokens,80);});
test('force refresh detects same-size replacement; removed sources clean FTS; pages clamp',async t=>{const {file,db}=fixture(t),store=db();fs.writeFileSync(file,JSON.stringify(message('alpha')));await store.scan([file]);const old=fs.statSync(file),id=store.list()[0].id;fs.writeFileSync(file,JSON.stringify(message('bravo')));fs.utimesSync(file,old.atime,old.mtime);await store.scan([file],()=>{},true);assert.equal(store.search({query:'bravo'}).length,1);assert.equal(store.records({id,offset:999999}).offset,0);await store.scan([]);assert.equal(store.list().length,0);assert.equal(store.search({query:'bravo'}).length,0);});
test('streamed derived exports contain valid complete JSON and raw source stays unchanged',async t=>{const {file,dir,db}=fixture(t),store=db();fs.writeFileSync(file,JSON.stringify(message('Привет <script>bad</script>')));const before=fs.readFileSync(file);await store.scan([file]);const id=store.list()[0].id;for(const format of ['md','json']){const dest=path.join(dir,'out.'+format);await store.writeExport({id,format,dest});const text=fs.readFileSync(dest,'utf8');assert.ok(text.includes('Привет'));if(format==='json')assert.equal(JSON.parse(text).records.length,1);}assert.deepEqual(fs.readFileSync(file),before);});
test('export rejects source folders, application data, hard links',async t=>{const {file,dir}=fixture(t);fs.writeFileSync(file,'source');await assert.rejects(checkDestination(file,[file]));await assert.rejects(checkDestination(path.join(dir,'out.json'),[dir]));await assert.rejects(checkDestination(file,[],[dir]));const link=path.join(dir,'hard.json');fs.linkSync(file,link);await assert.rejects(checkDestination(link,[]));const dest=path.join(dir,'safe.json');assert.equal((await checkDestination(dest,[])).exists,false);});
test('explicit service-session search works without exposing services globally',async t=>{const {file,db}=fixture(t),store=db();fs.writeFileSync(file,[{type:'session_meta',payload:{thread_source:'subagent'}},message('службовий контекст')].map(JSON.stringify).join('\n'));await store.scan([file]);assert.equal(store.search({query:'службов'}).length,0);assert.equal(store.search({query:'службов',sessionId:store.list()[0].id}).length,1);});
