const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const pkg=require('../package.json');
const runtime=path.resolve(process.env.ELECTRON_RUNTIME || path.join(root,'node_modules','electron','dist'));
const dest=path.resolve(root,'..',`SessionVault-${pkg.version}-Windows`);
if(process.platform!=='win32'||process.arch!=='x64')throw Error('Package on Windows x64.');
if(!fs.existsSync(path.join(runtime,'electron.exe')))throw Error('Run npm install, or set ELECTRON_RUNTIME to an extracted Electron Windows x64 runtime.');
if(fs.existsSync(dest))throw Error('Build output already exists. Move it aside before packaging: '+dest);
fs.mkdirSync(dest);
fs.cpSync(runtime,dest,{recursive:true});
const appDir=path.join(dest,'resources','app');fs.mkdirSync(appDir,{recursive:true});
for(const name of ['src','ui'])fs.cpSync(path.join(root,name),path.join(appDir,name),{recursive:true,filter:p=>!p.endsWith('.txt')});
fs.writeFileSync(path.join(appDir,'package.json'),JSON.stringify({name:pkg.name,productName:pkg.productName,version:pkg.version,description:pkg.description,main:pkg.main},null,2));
const exe=path.join(dest,'Session Vault.exe');fs.renameSync(path.join(dest,'electron.exe'),exe);
fs.writeFileSync(exe+'.version-resource',require('./version-resource.cjs')(pkg));
execFileSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(__dirname,'set-icon.ps1'),'-Executable',exe,'-Icon',path.join(root,'ui','icon.ico')],{stdio:'inherit',windowsHide:true});
fs.unlinkSync(exe+'.version-resource');
const defaultApp=path.join(dest,'resources','default_app.asar');if(fs.existsSync(defaultApp))fs.unlinkSync(defaultApp);
for(const name of ['README.md','ARCHITECTURE.md','VALIDATION.md','PROJECT_STATUS.md'])fs.copyFileSync(path.join(root,name),path.join(dest,name));
fs.cpSync(path.join(root,'docs'),path.join(dest,'docs'),{recursive:true});
fs.copyFileSync(path.join(root,'DESIGN_AUDIT.md'),path.join(dest,'DESIGN_AUDIT.md'));
fs.writeFileSync(path.join(dest,'BUILD.json'),JSON.stringify({product:pkg.productName,version:pkg.version,electron:fs.readFileSync(path.join(runtime,'version'),'utf8').trim(),platform:'win32',arch:'x64',builtAt:new Date().toISOString()},null,2));
fs.writeFileSync(path.join(dest,'START-HERE.txt'),'Open Session Vault.exe. Keep this entire folder together. No installation or account is required.\r\nUser data: %APPDATA%\\session-vault\r\nSource JSONL files are read-only. See README.md for usage and limitations.\r\n');
console.log(exe);
