window.helpContent={
 en:[
 ['What is a session?', 'A session is a local Codex JSONL log: messages, tool calls and technical events. Session Vault reads these files and creates a separate SQLite index. It does not edit Codex history or execute commands from conversations.'],
 ['Which source should I choose?', 'Automatic discovery scans your home folder’s .codex/sessions. Choose a folder to include its subfolders, or select individual JSONL files. Add keeps existing sources; Replace sources starts a new selection. Remove source deletes only its derived index. The originals stay where they are.'],
 ['What are service sessions?', 'Guardian reviews and subagent sessions are technical or delegated work recorded by Codex. They are hidden by default to keep the main history readable. Enable Service to include them in the list and global search. Their presence does not mean another person used your account. Unknown source types remain visible.'],
 ['Conversation and reading modes', 'Conversation shows user and assistant messages. All records adds instructions, injected context, tool activity and recorded reasoning summaries. Tools shows calls and outputs. Long messages expand on demand; pages contain 60 records. Source line numbers help locate the original. Attachments are placeholders; encrypted reasoning is not decoded.'],
 ['Overview, chapters and timeline', 'Overview counts facts recorded in the log; token totals are not a bill or context size. Chapters start at user messages and use their text as titles. Timeline follows source order, including tool calls, turn boundaries and context compaction. Select an item to read it; Back or Esc returns to the previous view.'],
 ['Topic graph and search', 'The graph counts words in user messages. Its spokes connect words to this session, not to semantic relationships. Select a word to search the session. Search matches word prefixes using SQLite FTS, supports Unicode and returns up to 100 matches. Multiple words are combined with AND. Original conversations are never translated.'],
 ['Missing, damaged and large files', 'A missing file remains readable from the existing cache while its source is connected. Refresh retries it when it reappears. Invalid lines are skipped and counted. Raw lines over 8 MB are skipped; indexed text is capped at 200,000 characters per record, approximately 64 million characters or 250,000 records per session. Warnings appear in the right panel. Search and derived exports cover only the index. Use original JSONL export for the full file.'],
 ['Where are my data and exports?', 'Settings shows connected paths and the local cache directory. The right panel can copy the selected file or folder path and show the original in Explorer. Markdown exports the dialogue; JSON exports normalized records; JSONL copies the original. Export cannot overwrite sources or application data. Private content may be included. Keep originals or exports as backups: the index alone is not a full archive.'],
 ['Keyboard and returning to work', 'Ctrl+K: search. Alt+1–6: views. Ctrl+B: left panel. Ctrl+Shift+B: right panel. F1: help. Esc: Back. Your session, page, reading position, filters, language and appearance are saved. Uncheck the welcome option or choose “Don’t show again” to resume directly next time. System follows the Windows light/dark setting.']
 ],
 ru:[
 ['Что такое сессия?', 'Сессия — локальный JSONL-журнал Codex: сообщения, вызовы инструментов и технические события. Session Vault читает эти файлы и создаёт отдельный индекс SQLite. Программа не редактирует историю Codex и не выполняет команды из разговоров.'],
 ['Как выбрать источник?', 'Автопоиск сканирует .codex/sessions в вашей домашней папке. Можно выбрать папку с подпапками или отдельные JSONL. «Добавить» сохраняет прежние источники; повторный выбор заменяет набор. Удаление источника убирает лишь производный индекс, оригиналы остаются на месте.'],
 ['Что такое служебные сессии?', 'Guardian review и subagent — технические проверки или делегированная работа Codex. Они скрыты по умолчанию. Кнопка «Служебные» включает их в список и глобальный поиск. Их наличие не означает, что вашим аккаунтом пользовался другой человек. Неизвестные типы источников остаются видимыми.'],
 ['Режимы чтения диалога', '«Простой диалог» показывает пользователя и ассистента. «Все записи» добавляет инструкции, внедрённый контекст, инструменты и доступные резюме рассуждения. «Инструменты» показывает вызовы и результаты. Длинные сообщения раскрываются; на странице 60 записей. Номер строки указывает на исходник. Вложения показаны обозначениями, зашифрованные рассуждения не расшифровываются.'],
 ['Обзор, главы и таймлайн', 'Обзор считает факты из журнала; токены не означают стоимость или размер контекста. Главы начинаются с сообщений пользователя, названия взяты из их текста. Таймлайн следует порядку исходника и включает инструменты, границы ходов и сжатие контекста. Нажмите запись, чтобы прочитать её; «Назад» или Esc возвращает на предыдущий экран.'],
 ['Граф тем и поиск', 'Граф считает слова в сообщениях пользователя. Линии связывают слова с сессией, а не обозначают семантические отношения. Нажатие слова запускает поиск в сессии. Поиск SQLite FTS поддерживает кириллицу и начало слова, показывает до 100 совпадений. Несколько слов объединяются условием И. Исходные разговоры не переводятся.'],
 ['Недоступные, повреждённые и большие файлы', 'Недоступный файл остаётся читаемым из кэша, пока его источник подключён. После возвращения файла нажмите обновление. Повреждённые строки пропускаются со счётчиком. Строки больше 8 МБ пропускаются; индекс ограничен 200 000 символов на запись, примерно 64 миллионами символов или 250 000 записей на сессию. Предупреждения — справа. Поиск и производный экспорт работают только по индексу; JSONL-экспорт сохраняет весь оригинал.'],
 ['Где данные и экспорт?', 'В настройках видны источники и каталог кэша. Справа можно скопировать путь файла или папки и открыть исходник в Проводнике. Markdown сохраняет диалог, JSON — нормализованные записи, JSONL — оригинал. Экспорт не перезаписывает источники и данные приложения. Возможна личная информация. Храните оригиналы или экспорты как резервные копии: индекс не заменяет полный архив.'],
 ['Клавиши и продолжение работы', 'Ctrl+K — поиск. Alt+1–6 — представления. Ctrl+B — левая панель. Ctrl+Shift+B — правая. F1 — справка. Esc — назад. Сессия, страница, позиция чтения, фильтры, язык и оформление сохраняются. Отключите приветствие в настройках или выберите «Больше не показывать», чтобы сразу продолжать работу. System следует светлому/тёмному режиму Windows.']
 ],
 uk:[
 ['Що таке сесія?', 'Сесія — локальний JSONL-журнал Codex: повідомлення, виклики інструментів і технічні події. Session Vault читає ці файли та створює окремий індекс SQLite. Програма не редагує історію Codex і не виконує команди з розмов.'],
 ['Як вибрати джерело?', 'Автопошук сканує .codex/sessions у вашій домашній папці. Можна вибрати папку з підпапками або окремі JSONL. «Додати» зберігає попередні джерела; повторний вибір замінює набір. Прибирання джерела видаляє лише похідний індекс, оригінали залишаються на місці.'],
 ['Що таке службові сесії?', 'Guardian review та subagent — технічні перевірки або делегована робота Codex. Вони приховані за замовчуванням. Кнопка «Службові» додає їх до списку й глобального пошуку. Їхня наявність не означає використання вашого облікового запису іншою людиною. Невідомі типи джерел залишаються видимими.'],
 ['Режими читання діалогу', '«Простий діалог» показує користувача й асистента. «Усі записи» додає інструкції, доданий контекст, інструменти та доступні підсумки міркування. «Інструменти» показує виклики й результати. Довгі повідомлення розгортаються; на сторінці 60 записів. Номер рядка вказує на оригінал. Вкладення показані позначками, зашифровані міркування не розшифровуються.'],
 ['Огляд, розділи та хронологія', 'Огляд підраховує факти з журналу; токени не означають вартість або розмір контексту. Розділи починаються з повідомлень користувача, назви взяті з їхнього тексту. Хронологія відповідає порядку джерела, включає інструменти, межі ходів і стиснення контексту. Натисніть запис, щоб прочитати його; «Назад» або Esc повертає на попередній екран.'],
 ['Граф тем і пошук', 'Граф підраховує слова в повідомленнях користувача. Лінії пов’язують слова із сесією, а не позначають семантичні відношення. Натискання слова запускає пошук у сесії. Пошук SQLite FTS підтримує кирилицю й початок слова, показує до 100 збігів. Кілька слів об’єднуються умовою І. Оригінальні розмови не перекладаються.'],
 ['Недоступні, пошкоджені та великі файли', 'Недоступний файл залишається читабельним із кешу, поки його джерело підключено. Після повернення файлу натисніть оновлення. Пошкоджені рядки пропускаються з лічильником. Рядки понад 8 МБ пропускаються; індекс обмежений 200 000 символами на запис, приблизно 64 мільйонами символів або 250 000 записів на сесію. Попередження — праворуч. Пошук і похідний експорт працюють лише за індексом; JSONL-експорт зберігає весь оригінал.'],
 ['Де дані й експорт?', 'У налаштуваннях видно джерела й каталог кешу. Праворуч можна скопіювати шлях до файлу чи папки та відкрити джерело в Провіднику. Markdown зберігає діалог, JSON — нормалізовані записи, JSONL — оригінал. Експорт не перезаписує джерела й дані програми. Можлива особиста інформація. Зберігайте оригінали або експорти як резервні копії: індекс не замінює повний архів.'],
 ['Клавіші й продовження роботи', 'Ctrl+K — пошук. Alt+1–6 — подання. Ctrl+B — ліва панель. Ctrl+Shift+B — права. F1 — довідка. Esc — назад. Сесія, сторінка, позиція читання, фільтри, мова та оформлення зберігаються. Вимкніть вітання в налаштуваннях або виберіть «Більше не показувати», щоб одразу продовжувати роботу. System відповідає світлому/темному режиму Windows.']
 ]
};

for(const [lang,text] of Object.entries({en:' Project views aggregate sessions sharing the same working directory. Choose session, project or whole vault and UTC dates. Timeline offers events, lanes, branching history and a calendar. Ctrl+P opens commands; Ctrl+L opens copied Session Vault references.',ru:' Представления проекта объединяют сессии с одинаковой рабочей папкой. Выберите сессию, проект или всё хранилище и даты UTC. В таймлайне доступны события, дорожки, ветви и календарь. Ctrl+P — команды; Ctrl+L — открыть скопированную ссылку Session Vault.',uk:' Подання проєкту об’єднують сесії з однаковою робочою папкою. Виберіть сесію, проєкт або все сховище й дати UTC. Таймлайн містить події, доріжки, гілки й календар. Ctrl+P — команди; Ctrl+L — відкрити скопійоване посилання Session Vault.'}))helpContent[lang][0][1]+=text;
for(const [lang,text] of Object.entries({en:' Automatic classifications use local text rules, not an AI model. Decisions/tasks are candidates and link to their source. Settings can enable manual annotations (off by default); annotations survive index rebuilds and never edit originals. Turning editing off keeps saved annotations visible. Chapters group records by UTC day; they are not generated narrative summaries.',ru:' Автоматическая классификация использует локальные правила текста, не AI-модель. Решения и задачи предположительны и имеют ссылку на источник. В настройках можно включить ручные отметки (по умолчанию выключены); они переживают пересоздание индекса и не меняют оригиналы. Отключение редактирования не скрывает сохранённые отметки. Главы группируют записи по дням UTC, это не сгенерированные резюме.',uk:' Автоматична класифікація використовує локальні правила тексту, не AI-модель. Рішення й завдання припустимі та мають посилання на джерело. У налаштуваннях можна дозволити ручні позначки (типово вимкнено); вони зберігаються після перебудови індексу й не змінюють оригінали. Вимкнення редагування не приховує збережені позначки. Розділи групують записи за днями UTC, це не згенеровані резюме.'}))helpContent[lang][3][1]+=text;

for(const [lang,text] of Object.entries({en:'Overview aggregates sessions in the selected project or scope. Chapters group records by UTC day; the session outline remains available. Timeline offers an event feed, horizontal view, lanes, recorded parent branches and an activity calendar. Select an event to inspect its source; Back returns to the previous view.',ru:'Обзор объединяет сессии выбранного проекта или области. Главы группируют записи по дням UTC; оглавление одной сессии доступно отдельно. Таймлайн содержит список, горизонтальный вид, дорожки, записанные связи ветвлений и календарь. Выберите событие для просмотра источника; «Назад» возвращает к предыдущему экрану.',uk:'Огляд об’єднує сесії вибраного проєкту або області. Розділи групують записи за днями UTC; зміст однієї сесії доступний окремо. Хронологія містить список, горизонтальне подання, доріжки, записані зв’язки гілок і календар. Виберіть подію для перегляду джерела; «Назад» повертає до попереднього екрана.'}))helpContent[lang][4][1]=text;
for(const [lang,text] of Object.entries({en:'The entity map connects sessions, candidate decisions/tasks, mentioned files and keywords. Links mean containment, mention or recorded parent, not causality. The frequency-only graph is also available. Search uses Unicode SQLite FTS with word prefixes and AND, up to 100 results. Conversations are never translated.',ru:'Карта связывает сессии, предполагаемые решения/задачи, упомянутые файлы и слова. Линии означают включение, упоминание или записанного родителя, не причинность. Частотный граф также доступен. Поиск SQLite FTS поддерживает кириллицу, префиксы и условие И, до 100 результатов. Разговоры не переводятся.',uk:'Карта поєднує сесії, припустимі рішення/завдання, згадані файли й слова. Лінії означають включення, згадування або записаного батька, не причинність. Частотний граф також доступний. Пошук SQLite FTS підтримує кирилицю, префікси та умову І, до 100 результатів. Розмови не перекладаються.'}))helpContent[lang][5][1]=text;

for(const [lang,text] of Object.entries({en:' Horizontal and swimlane views group nearby events into count cards. Click a group to open its paginated list below, then a record to inspect its source. A single-event card opens the inspector directly. Fit adjusts the timeline width; zoom changes grouping, not font size.',ru:' В горизонтальном виде и дорожках близкие события объединяются в карточки со счётчиком. Нажмите группу, чтобы открыть список ниже, затем запись для просмотра источника. Одиночная карточка сразу открывает инспектор. «Уместить» подгоняет ширину; масштаб меняет группировку, а не размер текста.',uk:' У горизонтальному поданні та доріжках близькі події об’єднано в картки з лічильником. Натисніть групу, щоб відкрити список нижче, потім запис для перегляду джерела. Одиночна картка одразу відкриває інспектор. «Вмістити» підганяє ширину; масштаб змінює групування, а не розмір тексту.'}))helpContent[lang][4][1]+=text;
